### ISSUE TITLE
你好 关于MOVIE

### ISSUE THREAD

**Issue by se11en** [LongguangWang/Video-Quality-Assessment#1]
你好：
前几天拜读你的文章，文章中提及了MOVIE，然后我看到你这边有MOVIE的压缩包，但是我在阅读了README以及里面相关的代码后，依然不知道该如何使用它，请问你能简单介绍吗?谢谢！

**Comment by LongguangWang** [comment]
你好。首先请根据MOVIE网页中的介绍对压缩包内的文件进行编译，得到movie.exe；之后根据压缩包里readme的介绍，用命令行调用相应的指令。需要注意的是，待测视频需要转至yuv格式。

**Comment by se11en** [comment]
谢谢你的回复，我下载了一下MOVIE网页里面那个加密的压缩包，比你上传的压缩包里面多一个项目文件(.vcproj），请问这个文件是没有作用吗。
我是编程小白，如果问题比较无脑请包涵，谢谢。。

**Comment by se11en** [comment]
我经过一系列操作能够配置GSL，并编译出MOVIE.EXE，但是遇到很多报错，我的环境是VS2005+WIN10，我觉得可能是环境的问题，能请教一下你是在什么环境编译成功的吗，谢谢

**Comment by se11en** [comment]
成功了，主要是GSL的配置问题。
如果有其他人遇到相同问题的话，这个链接可能有所帮助
[https://download.csdn.net/download/neddy123456/1742171](url)

**Comment by wwlCape** [comment]
could you give me the key to the software? I sent an email to the author, but don't get a reply so far. @LongguangWang @se11en
